version: '3'

services:
 app:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - .:/app/
   command: "python manage.py runserver 0.0.0.0:8000"

   depends_on: 
    - db
 db:
   image: mysql:latest

   command: mysqld --default-authentication-plugin=mysql_native_password
   volumes:
     - "/var/lib/mysql:/var/lib/mysql"
   ports:
     - "3306:3306"
   restart: always
   environment: 
     MYSQL_ROOT_PASSWORD: "Capricorn111@mysql"
     MYSQL_DATABASE: "django_app"
     MYSQL_USER : "python"
     MYSQL_PASSWORD : "python"

      